---
name: mychannel.firstnetwork.connectionprofile
x-type: "hlfv1"
description: "BankPeerContract methods will be used through this profile"
version: "1.0"

channels:
  mychannel:
    orderers:
      - orderer1-org0
      - orderer2-org0
      - orderer3-org0
    peers:
      peer1-org1:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      peer1-org2:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      peer1-org3:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

organizations:
  Org1:
    mspid: org1MSP
    peers:
      - peer1-org1
    certificateAuthorities:
      - rca-org1
    adminPrivateKey:
      path: /opt/aibc/guide/hyperledger/org1/admin/msp/keystore/1b82e5e2cc75aac9f422982d15f5354f3f4d4843bca18a38b4f6ae28c32abdc9_sk
    signedCert:
      path: /opt/aibc/guide/hyperledger/org1/admin/msp/signcerts/cert.pem
  
  Org2:
    mspid: org2MSP
    peers:
      - peer1-org2
    certificateAuthorities:
      - rca-org2
    adminPrivateKey:
      path: /opt/aibc/guide/hyperledger/org3/admin/msp/keystore/02b630058ea359d21e898113612e264e9337a37e1722876fbade4ace9c55b042_sk
    signedCert:
      path: /opt/aibc/guide/hyperledger/org2/admin/msp/signcerts/cert.pem

  Org3:
    mspid: org3MSP
    peers:
      - peer1-org3
    certificateAuthorities:
      - rca-org3
    adminPrivateKey:
      path: /opt/aibc/guide/hyperledger/org3/admin/msp/keystore/02b630058ea359d21e898113612e264e9337a37e1722876fbade4ace9c55b042_sk
    signedCert:
      path: /opt/aibc/guide/hyperledger/org3/admin/msp/signcerts/cert.pem

orderers:
  orderer1-org0:
    url: grpcs://localhost:7050
    grpcOptions:
      ssl-target-name-override: orderer1-org0
    tlsCACerts:
      path: /opt/aibc/guide/hyperledger/org0/orderer/tls-msp/tlscacerts/tls-0-0-0-0-7052.pem

  orderer2-org0:
    url: grpcs://localhost:8050
    grpcOptions:
      ssl-target-name-override: orderer2-org0
    tlsCACerts:
      path: /opt/aibc/guide/hyperledger/org0/orderer2/tls-msp/tlscacerts/tls-0-0-0-0-7052.pem 
      
  orderer3-org0:
    url: grpcs://localhost:9050
    grpcOptions:
      ssl-target-name-override: orderer3-org0
    tlsCACerts:
      path: /opt/aibc/guide/hyperledger/org0/orderer3/tls-msp/tlscacerts/tls-0-0-0-0-7052.pem

peers:
  peer1-org1:
    url: grpcs://localhost:7051
    grpcOptions:
      ssl-target-name-override: peer1-org1
      request-timeout: 120001
    tlsCACerts:
      path: /opt/aibc/guide/hyperledger/org1/peer1/tls-msp/tlscacerts/tls-0-0-0-0-7052.pem

  peer1-org2:
    url: grpcs://localhost:9051
    grpcOptions:
      ssl-target-name-override: peer1-org2
      request-timeout: 120001
    tlsCACerts:
      path: /opt/aibc/guide/hyperledger/org2/peer1/tls-msp/tlscacerts/tls-0-0-0-0-7052.pem
 
  peer1-org3:
    url: grpcs://localhost:11051
    grpcOptions:
      ssl-target-name-override: peer1-org3
      request-timeout: 120001
    tlsCACerts:
      path: /opt/aibc/guide/hyperledger/org3/peer1/tls-msp/tlscacerts/tls-0-0-0-0-7052.pem


certificateAuthorities:
  rca-org1:
    url: https://localhost:7054
    httpOptions:
      verify: false
    tlsCACerts:
      path: /opt/aibc/guide/hyperledger/org1/ca/crypto/ca-cert.pem
    registrar:
      - enrollId: rca-org1-admin
        enrollSecret: rca-org1-adminpw
    caName: rca-org1

  rca-org2:
    url: https://localhost:7055
    httpOptions:
      verify: false
    tlsCACerts:
      path: /opt/aibc/guide/hyperledger/org2/ca/crypto/ca-cert.pem
    registrar:
      - enrollId: rca-org2-admin
        enrollSecret: rca-org2-adminpw
    caName: rca-org2

  rca-org3:
    url: https://localhost:7056
    httpOptions:
      verify: false
    tlsCACerts:
      path: /opt/aibc/guide/hyperledger/org3/ca/crypto/ca-cert.pem
    registrar:
      - enrollId: rca-org3-admin
        enrollSecret: rca-org3-adminpw
    caName: rca-org3
